### ISSUE TITLE
A "verbose" option should be present, which returns all calculated latency data to the user.

### ISSUE THREAD

**Issue by Aendir** [Saunved/isfastnet#1]
In case someone wants to add their own processing on top of the latency data, the script should enable the user to fetch all relevant data used in calculating the latency.
Right now, the following values appear to be useful if returned by the proposed "verbose" option.
    
    1. The calculated average latency.
    2. The threshold value used.
    3. The list of all latency values that were found.

**Comment by Aendir** [comment]
I can take this up if it's okay.

**Comment by Saunved** [comment]
Hey, that sounds great! Feel free to raise a PR :smile:
